version: '3'

services:
  sentiment-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: reddit-sentiment-app
    restart: unless-stopped
    ports:
      - "8501:8501"  # Expose Streamlit UI port
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
    environment:
      - TZ=America/New_York  # Set timezone to Boston
      - REDDIT_JSON_URL=${REDDIT_JSON_URL}
      - DEMO_MODE=${DEMO_MODE:-false}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_RECIPIENT=${EMAIL_RECIPIENT}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s